name: nekoton_bridge_workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - packages/nekoton_bridge
  - packages/flutter_nekoton_bridge
  - packages/flutter_nekoton_bridge/example

dev_dependencies:
  melos: ^7.1.0

melos:
  scripts:
    analyze:
      exec: flutter analyze .
      description: Analyze a specific package in this project.

    check-format:
      exec: dart format --set-exit-if-changed .
      description: Check the format of a specific package in this project.

    check-rust:
      exec: rustfmt --check --edition 2021 rust/src/lib.rs && cargo clippy -- -D warnings
      description: Check the format of a rust code.
      packageFilters:
        dirExists: rust

    format:
      exec: dart format .
      description: Format a specific package in this project.

    build:
      run: melos run build:ios && melos run build:android
      description: Build all native libraries for the project.

    codegen:
      run: bash scripts/codegen.sh
      description: Generate code.

    git-check:
      run: bash scripts/git-check.sh
      description: Check if some code changed during build

    build:ios:
      run: bash scripts/build-ios.sh
      description: Build the XCFramework for iOS.

    build:android:
      run: bash scripts/build-android.sh
      description: Build the .tar.gz for Android.

    test:
      run: melos run test:dart --no-select && melos run test:flutter --no-select
      description: Run all Dart & Flutter tests in this project.

    test:dart:
      run: melos exec -c 1 --fail-fast -- "dart test test"
      description: Run Dart tests for a specific package in this project.
      packageFilters:
        flutter: false
        dirExists: test

    test:flutter:
      run: melos exec -c 1 --fail-fast -- "flutter test test"
      description: Run Flutter tests for a specific package in this project.
      packageFilters:
        flutter: true
        dirExists: test

    test:integration:
      run: melos exec -c 1 --fail-fast -- "flutter test integration_test"
      description: Run Flutter teintegration teststs for a specific package in this project.
      packageFilters:
        flutter: true
        dirExists: integration_test

    check-all:
      description: Prepare to commit by checking all things
      run: melos analyze && melos check-format && melos check-rust && melos test && melos test:integration

    clean-example:
      run: bash scripts/clean-example.sh
      description: Clean example for rebuilding after FNB update

  command:
    clean:
      hooks:
        post: bash scripts/clean.sh
    version:
      updateGitTagRefs: true
      hooks:
        preCommit: bash scripts/version.sh
