name: nekoton_bridge
description: Nekoton bridge
version: 1.15.0
homepage: https://github.com/broxus/nekoton_bridge.git
repository: https://github.com/broxus/nekoton_bridge.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.1.0
  test: ^1.23.1
  freezed: ^2.4.1
  build_runner: ^2.4.4

dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.78.0
  freezed_annotation: ^2.2.0
  basic_utils: ^5.5.1
  flutter_lints: ^2.0.1
  money2_improver: ^1.3.1
  money2: ^4.0.0
  meta: ^1.9.1
  uuid: ^3.0.7
